In [59]:
from scipy.io import loadmat
import numpy as np
data = loadmat(r"C:\Users\Aashish\Desktop\EC400\code_amal_sir\test_data.mat")
print(data)

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Thu Oct 13 04:32:23 2022', '__version__': '1.0', '__globals__': [], 'my_data': array([[2, 3, 4, 1, 9],
       [0, 2, 5, 1, 3],
       [8, 6, 4, 2, 1],
       [0, 4, 5, 1, 3]], dtype=uint8)}


In [60]:
x = data["my_data"]

In [61]:
print(x)

[[2 3 4 1 9]
 [0 2 5 1 3]
 [8 6 4 2 1]
 [0 4 5 1 3]]


In [62]:
x[0][1] = 2.5
print(min(x[:,0]))


0


In [63]:
features = x
for k in range(4):  #Last 2 columns ko chhorna h (ie 214 and 215):
    for l in range(4):
        features[k][l]=np.float64(features[k][l])

print(features)
# for k in range(5):  #Last 2 columns ko chhorna h (ie 214 and 215)
    
#     features[:,k]=features[:,k]/max(features[:,k])
# #      features(:,k)=features(:,k)/max(features(:,k))

[[2 2 4 1 9]
 [0 2 5 1 3]
 [8 6 4 2 1]
 [0 4 5 1 3]]


In [64]:
print(features)

[[2 2 4 1 9]
 [0 2 5 1 3]
 [8 6 4 2 1]
 [0 4 5 1 3]]


In [65]:
print(type(features[0][0]))

<class 'numpy.uint8'>
